using System.ComponentModel.DataAnnotations.Schema;
using Workneering.Base.Domain.Interfaces;

namespace Workneering.Base.Domain.Common;

public record BaseEntity : ISoftDelete, ICreatedAuditableEntity, IModifiedAuditableEntity
{
    protected Guid _id = Guid.NewGuid();
    [DatabaseGenerated(DatabaseGeneratedOption.None)] //this indicates that the property value is not generated by the database.
    public Guid Id { get => _id; private set => _id = value; }
    public bool IsDeleted { get; private set; }
    public DateTimeOffset? DeletedDate { get; private set; }
    public Guid? DeletedBy { get; private set; }
    public DateTimeOffset CreatedDate { get; private set; }

    public Guid? CreatedBy { get; private set; }

    public DateTimeOffset? LastModifiedDate { get; private set; }

    public Guid? LastModifiedBy { get; private set; }

    public void MarkAsCreated(Guid? userId)
    {
        CreatedDate = DateTimeOffset.UtcNow;
        CreatedBy = userId;
    }

    public void MarkAsModified(Guid? userId)
    {
        LastModifiedDate = DateTimeOffset.UtcNow;
        LastModifiedBy = userId;
    }
    public void MarkAsDeleted(Guid? userId)
    {
        IsDeleted = true;
        DeletedDate = DateTimeOffset.UtcNow;
        DeletedBy = userId;
    }

    public void MarkAsNotDeleted()
    {
        IsDeleted = false;
        DeletedBy = null;

    }

    // domain event
    public readonly List<BaseEvent> _domainEvents = new();
    [NotMapped]
    public IReadOnlyCollection<BaseEvent> DomainEvents => _domainEvents.AsReadOnly();
    public void RemoveDomainEvent(BaseEvent domainEvent)
    {
        _domainEvents.Remove(domainEvent);
    }

    public void ClearDomainEvents()
    {
        _domainEvents.Clear();
    }

}